httpClient:
  timeout: 3600000ms
  connectionTimeout: 20000ms
  connectionRequestTimeout: 20000ms

logging:
  appenders:
    - type: console
      threshold: DEBUG
      target: stdout
      logFormat: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%30.30t] %-30.30c{1} %mdc{} %-5p %m%n"
    - type: file
      threshold: DEBUG
      logFormat: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%30.30t] %-30.30c{1} %mdc{} %-5p %m%n"
      currentLogFilename: /var/log/sft/sft-agent.log
      archivedLogFilenamePattern: /var/log/sft-agent-%d.log.gz
      archivedFileCount: 7
      timeZone: UTC

apikey: Te5tAp1Key

<#include "agent-application-config.yml">
