name: PR

on:
  pull_request:
    paths-ignore:
      - 'ci/**'
      - '**/*.md'

jobs:
  docker-build-and-scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [sft-agent, sft-agent-ingress]
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -t dwpdigital/${{ matrix.image }}:latest -f ${{ matrix.image }}/Dockerfile .
      - name: Run Snyk to check image for high vulnerabilities
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: dwpdigital/${{ matrix.image }}
          args: --file=${{ matrix.image }}/Dockerfile --policy-path=./.snyk --severity-threshold=high --exclude-base-image-vulns --org=dwp-dataworks
